name: CI/CD Pipeline

on:
  push:
    branches: [develop]

jobs:
    deploy:
        runs-on: ubuntu-latest
        name: Deploy to Development
        steps:
          - name: Deploy
            run: echo "Deploying to Development..."