name: CI/CD Pipeline

on:
  pull_request:
    branches: [develop]

jobs:
    build:
        runs-on: ubuntu-latest
        name : Build and Test
        steps:
          - name: Build
            run: echo "Building the project..."

    test:
        runs-on: ubuntu-latest
        needs: build
        name: Run Tests
        steps:
          - name: Test
            run: echo "Running tests..."